// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhanMemQuanLyKhachSan.Model;

#nullable disable

namespace PMQuanLyKhachSan.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260718091114_PMQuanLyKhachSan")]
    partial class PMQuanLyKhachSan
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.ChiTietDichVu", b =>
                {
                    b.Property<int>("MaCTDV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTDV"), 1L, 1);

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDV")
                        .HasColumnType("int");

                    b.Property<int>("MaDatPhong")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaCTDV");

                    b.HasIndex("MaDV");

                    b.HasIndex("MaDatPhong");

                    b.ToTable("ChiTietDichVus");

                    b.HasData(
                        new
                        {
                            MaCTDV = 1,
                            DonGia = 100000m,
                            MaDV = 1,
                            MaDatPhong = 1,
                            SoLuong = 2,
                            ThanhTien = 200000m
                        },
                        new
                        {
                            MaCTDV = 2,
                            DonGia = 50000m,
                            MaDV = 2,
                            MaDatPhong = 1,
                            SoLuong = 3,
                            ThanhTien = 150000m
                        },
                        new
                        {
                            MaCTDV = 3,
                            DonGia = 300000m,
                            MaDV = 4,
                            MaDatPhong = 2,
                            SoLuong = 1,
                            ThanhTien = 300000m
                        },
                        new
                        {
                            MaCTDV = 4,
                            DonGia = 400000m,
                            MaDV = 5,
                            MaDatPhong = 2,
                            SoLuong = 1,
                            ThanhTien = 400000m
                        },
                        new
                        {
                            MaCTDV = 5,
                            DonGia = 200000m,
                            MaDV = 3,
                            MaDatPhong = 4,
                            SoLuong = 2,
                            ThanhTien = 400000m
                        });
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaCTHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTHD"), 1L, 1);

                    b.Property<int?>("MaCTDV")
                        .HasColumnType("int");

                    b.Property<int?>("MaDatPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaHD")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaCTHD");

                    b.HasIndex("MaCTDV");

                    b.HasIndex("MaDatPhong");

                    b.HasIndex("MaHD");

                    b.ToTable("ChiTietHoaDons");

                    b.HasData(
                        new
                        {
                            MaCTHD = 1,
                            MaDatPhong = 1,
                            MaHD = 1,
                            ThanhTien = 1000000m
                        },
                        new
                        {
                            MaCTHD = 2,
                            MaCTDV = 1,
                            MaHD = 1,
                            ThanhTien = 200000m
                        },
                        new
                        {
                            MaCTHD = 3,
                            MaCTDV = 2,
                            MaHD = 1,
                            ThanhTien = 150000m
                        },
                        new
                        {
                            MaCTHD = 4,
                            MaDatPhong = 2,
                            MaHD = 2,
                            ThanhTien = 1800000m
                        },
                        new
                        {
                            MaCTHD = 5,
                            MaCTDV = 3,
                            MaHD = 2,
                            ThanhTien = 300000m
                        },
                        new
                        {
                            MaCTHD = 6,
                            MaCTDV = 4,
                            MaHD = 2,
                            ThanhTien = 400000m
                        },
                        new
                        {
                            MaCTHD = 7,
                            MaDatPhong = 3,
                            MaHD = 3,
                            ThanhTien = 1200000m
                        },
                        new
                        {
                            MaCTHD = 8,
                            MaDatPhong = 4,
                            MaHD = 4,
                            ThanhTien = 900000m
                        },
                        new
                        {
                            MaCTHD = 9,
                            MaCTDV = 5,
                            MaHD = 4,
                            ThanhTien = 400000m
                        },
                        new
                        {
                            MaCTHD = 10,
                            MaDatPhong = 5,
                            MaHD = 5,
                            ThanhTien = 2400000m
                        });
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.ChucVu", b =>
                {
                    b.Property<int>("MaChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChucVu"), 1L, 1);

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaChucVu");

                    b.ToTable("ChucVus");

                    b.HasData(
                        new
                        {
                            MaChucVu = 1,
                            TenChucVu = "Quản lý"
                        },
                        new
                        {
                            MaChucVu = 2,
                            TenChucVu = "Lễ tân"
                        },
                        new
                        {
                            MaChucVu = 3,
                            TenChucVu = "Lao công"
                        },
                        new
                        {
                            MaChucVu = 4,
                            TenChucVu = "Đầu bếp"
                        },
                        new
                        {
                            MaChucVu = 5,
                            TenChucVu = "Phục vụ nhà hàng"
                        },
                        new
                        {
                            MaChucVu = 6,
                            TenChucVu = "Bảo vệ"
                        });
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.DatPhong", b =>
                {
                    b.Property<int>("MaDatPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDatPhong"), 1L, 1);

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaDatPhong");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaPhong");

                    b.ToTable("DatPhongs");

                    b.HasData(
                        new
                        {
                            MaDatPhong = 1,
                            MaKH = 1,
                            MaPhong = 102,
                            NgayDat = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayNhan = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTra = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Đã đặt"
                        },
                        new
                        {
                            MaDatPhong = 2,
                            MaKH = 2,
                            MaPhong = 202,
                            NgayDat = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayNhan = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTra = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Đang ở"
                        },
                        new
                        {
                            MaDatPhong = 3,
                            MaKH = 3,
                            MaPhong = 301,
                            NgayDat = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayNhan = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTra = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Đã thanh toán"
                        },
                        new
                        {
                            MaDatPhong = 4,
                            MaKH = 4,
                            MaPhong = 303,
                            NgayDat = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayNhan = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTra = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Đang hủy"
                        },
                        new
                        {
                            MaDatPhong = 5,
                            MaKH = 5,
                            MaPhong = 305,
                            NgayDat = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayNhan = new DateTime(2026, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTra = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Đã trả phòng"
                        });
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.DichVu", b =>
                {
                    b.Property<int>("MaDV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDV"), 1L, 1);

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenDV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDV");

                    b.ToTable("DichVus");

                    b.HasData(
                        new
                        {
                            MaDV = 1,
                            Gia = 250000m,
                            TenDV = "Ăn uống"
                        },
                        new
                        {
                            MaDV = 2,
                            Gia = 50000m,
                            TenDV = "Giặt ủi"
                        },
                        new
                        {
                            MaDV = 3,
                            Gia = 200000m,
                            TenDV = "Thuê xe máy"
                        },
                        new
                        {
                            MaDV = 4,
                            Gia = 300000m,
                            TenDV = "Đưa đón sân bay"
                        },
                        new
                        {
                            MaDV = 5,
                            Gia = 400000m,
                            TenDV = "Spa"
                        });
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.HoaDon", b =>
                {
                    b.Property<int>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHD"), 1L, 1);

                    b.Property<int>("MaDatPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucTT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHD");

                    b.HasIndex("MaDatPhong");

                    b.ToTable("HoaDons");

                    b.HasData(
                        new
                        {
                            MaHD = 1,
                            MaDatPhong = 1,
                            NgayLap = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhuongThucTT = "Tiền mặt",
                            TongTien = 1350000m
                        },
                        new
                        {
                            MaHD = 2,
                            MaDatPhong = 2,
                            NgayLap = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhuongThucTT = "Chuyển khoản",
                            TongTien = 2500000m
                        },
                        new
                        {
                            MaHD = 3,
                            MaDatPhong = 3,
                            NgayLap = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhuongThucTT = "Tiền mặt",
                            TongTien = 1200000m
                        },
                        new
                        {
                            MaHD = 4,
                            MaDatPhong = 4,
                            NgayLap = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhuongThucTT = "Thẻ",
                            TongTien = 1300000m
                        },
                        new
                        {
                            MaHD = 5,
                            MaDatPhong = 5,
                            NgayLap = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhuongThucTT = "Chuyển khoản",
                            TongTien = 2400000m
                        });
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"), 1L, 1);

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKH");

                    b.ToTable("KhachHangs");

                    b.HasData(
                        new
                        {
                            MaKH = 1,
                            CCCD = "00111111",
                            GioiTinh = true,
                            HoTen = "Nguyễn Minh Anh",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2001, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0901111111",
                            TenDangNhap = "anh"
                        },
                        new
                        {
                            MaKH = 2,
                            CCCD = "00222222",
                            GioiTinh = true,
                            HoTen = "Trần Quốc Bảo",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2000, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0902222222",
                            TenDangNhap = "bao"
                        },
                        new
                        {
                            MaKH = 3,
                            CCCD = "00333333",
                            GioiTinh = true,
                            HoTen = "Lê Thanh Bình",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2002, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0903333333",
                            TenDangNhap = "binh"
                        },
                        new
                        {
                            MaKH = 4,
                            CCCD = "00444444",
                            GioiTinh = false,
                            HoTen = "Phạm Gia Hân",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2003, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0904444444",
                            TenDangNhap = "han"
                        },
                        new
                        {
                            MaKH = 5,
                            CCCD = "00555555",
                            GioiTinh = false,
                            HoTen = "Đỗ Thu Hà",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2001, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0905555555",
                            TenDangNhap = "ha"
                        },
                        new
                        {
                            MaKH = 6,
                            CCCD = "00666666",
                            GioiTinh = true,
                            HoTen = "Nguyễn Văn Nam",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(1999, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0906666666",
                            TenDangNhap = "nam"
                        },
                        new
                        {
                            MaKH = 7,
                            CCCD = "00777777",
                            GioiTinh = false,
                            HoTen = "Bùi Thị Ngọc",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2002, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0907777777",
                            TenDangNhap = "ngoc"
                        },
                        new
                        {
                            MaKH = 8,
                            CCCD = "00888888",
                            GioiTinh = true,
                            HoTen = "Hoàng Đức Long",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2000, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0908888888",
                            TenDangNhap = "long"
                        },
                        new
                        {
                            MaKH = 9,
                            CCCD = "00999999",
                            GioiTinh = false,
                            HoTen = "Nguyễn Thị Hồng",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(2001, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0909999999",
                            TenDangNhap = "hong"
                        },
                        new
                        {
                            MaKH = 10,
                            CCCD = "01010101",
                            GioiTinh = true,
                            HoTen = "Vũ Mạnh Cường",
                            MatKhau = "123456789",
                            NgaySinh = new DateTime(1998, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0910101010",
                            TenDangNhap = "cuong"
                        });
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.LichPhanCong", b =>
                {
                    b.Property<int>("MaLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLich"), 1L, 1);

                    b.Property<string>("CaLam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLam")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLich");

                    b.HasIndex("MaNV");

                    b.ToTable("LichPhanCongs");

                    b.HasData(
                        new
                        {
                            MaLich = 1,
                            CaLam = "Sáng",
                            GhiChu = "",
                            GioBatDau = new TimeSpan(0, 7, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 11, 30, 0, 0),
                            MaNV = 1,
                            NgayLam = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLich = 2,
                            CaLam = "Chiều",
                            GhiChu = "",
                            GioBatDau = new TimeSpan(0, 13, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 17, 0, 0, 0),
                            MaNV = 2,
                            NgayLam = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLich = 3,
                            CaLam = "Tối",
                            GhiChu = "",
                            GioBatDau = new TimeSpan(0, 17, 30, 0, 0),
                            GioKetThuc = new TimeSpan(0, 22, 0, 0, 0),
                            MaNV = 3,
                            NgayLam = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLich = 4,
                            CaLam = "Sáng",
                            GhiChu = "",
                            GioBatDau = new TimeSpan(0, 7, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 11, 30, 0, 0),
                            MaNV = 4,
                            NgayLam = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLich = 5,
                            CaLam = "Chiều",
                            GhiChu = "",
                            GioBatDau = new TimeSpan(0, 13, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 17, 0, 0, 0),
                            MaNV = 5,
                            NgayLam = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLich = 6,
                            CaLam = "Tối",
                            GhiChu = "",
                            GioBatDau = new TimeSpan(0, 17, 30, 0, 0),
                            GioKetThuc = new TimeSpan(0, 22, 0, 0, 0),
                            MaNV = 6,
                            NgayLam = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLich = 7,
                            CaLam = "Sáng",
                            GhiChu = "",
                            GioBatDau = new TimeSpan(0, 7, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 11, 30, 0, 0),
                            MaNV = 7,
                            NgayLam = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLich = 8,
                            CaLam = "Chiều",
                            GhiChu = "",
                            GioBatDau = new TimeSpan(0, 13, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 17, 0, 0, 0),
                            MaNV = 8,
                            NgayLam = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLich = 9,
                            CaLam = "Tối",
                            GhiChu = "",
                            GioBatDau = new TimeSpan(0, 17, 30, 0, 0),
                            GioKetThuc = new TimeSpan(0, 22, 0, 0, 0),
                            MaNV = 9,
                            NgayLam = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLich = 10,
                            CaLam = "Sáng",
                            GhiChu = "",
                            GioBatDau = new TimeSpan(0, 7, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 11, 30, 0, 0),
                            MaNV = 10,
                            NgayLam = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.LoaiPhong", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"), 1L, 1);

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiPhongs");

                    b.HasData(
                        new
                        {
                            MaLoai = 1,
                            Gia = 3000000m,
                            MoTa = "Phòng phù hợp cho 2 người lớn và 1 trẻ em",
                            TenLoai = "Standard 1 giường đôi"
                        },
                        new
                        {
                            MaLoai = 2,
                            Gia = 3500000m,
                            MoTa = "Phòng phù hợp cho 2 người lớn",
                            TenLoai = "Standard 2 giường đơn"
                        },
                        new
                        {
                            MaLoai = 3,
                            Gia = 5000000m,
                            MoTa = "Phòng phù hợp cho 2 người lớn và 2 trẻ em",
                            TenLoai = "Deluxe 1 giường đôi"
                        },
                        new
                        {
                            MaLoai = 4,
                            Gia = 7000000m,
                            MoTa = "Phòng phù hợp cho 4 người lớn",
                            TenLoai = "Deluxe 2 giường đôi"
                        },
                        new
                        {
                            MaLoai = 5,
                            Gia = 8000000m,
                            MoTa = "Phòng cao cấp phù hợp cho 2 người lớn và 2 trẻ em",
                            TenLoai = "Suite"
                        });
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"), 1L, 1);

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaChucVu")
                        .HasColumnType("int");

                    b.Property<int>("MaTK")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaNV");

                    b.HasIndex("MaChucVu");

                    b.ToTable("NhanViens");

                    b.HasData(
                        new
                        {
                            MaNV = 1,
                            Email = "huong@gmail.com",
                            GioiTinh = false,
                            HoTen = "Lương Thị Quỳnh Hương",
                            MaChucVu = 1,
                            MaTK = 1,
                            NgaySinh = new DateTime(2005, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0976111111"
                        },
                        new
                        {
                            MaNV = 2,
                            Email = "hay@gmail.com",
                            GioiTinh = false,
                            HoTen = "Trịnh Thị Hay",
                            MaChucVu = 1,
                            MaTK = 2,
                            NgaySinh = new DateTime(2005, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0982222222"
                        },
                        new
                        {
                            MaNV = 3,
                            Email = "diem@gmail.com",
                            GioiTinh = false,
                            HoTen = "Nguyễn Thị Diễm",
                            MaChucVu = 1,
                            MaTK = 3,
                            NgaySinh = new DateTime(2005, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0983333333"
                        },
                        new
                        {
                            MaNV = 4,
                            Email = "an@gmail.com",
                            GioiTinh = true,
                            HoTen = "Nguyễn Văn An",
                            MaChucVu = 2,
                            MaTK = 4,
                            NgaySinh = new DateTime(1999, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0984444444"
                        },
                        new
                        {
                            MaNV = 5,
                            Email = "mai@gmail.com",
                            GioiTinh = false,
                            HoTen = "Phạm Thị Mai",
                            MaChucVu = 2,
                            MaTK = 5,
                            NgaySinh = new DateTime(2000, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0985555555"
                        },
                        new
                        {
                            MaNV = 6,
                            Email = "tung@gmail.com",
                            GioiTinh = true,
                            HoTen = "Lê Văn Tùng",
                            MaChucVu = 3,
                            MaTK = 6,
                            NgaySinh = new DateTime(1998, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0986666666"
                        },
                        new
                        {
                            MaNV = 7,
                            Email = "lan@gmail.com",
                            GioiTinh = false,
                            HoTen = "Đỗ Thị Lan",
                            MaChucVu = 4,
                            MaTK = 7,
                            NgaySinh = new DateTime(1997, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0987777777"
                        },
                        new
                        {
                            MaNV = 8,
                            Email = "binh@gmail.com",
                            GioiTinh = true,
                            HoTen = "Hoàng Văn Bình",
                            MaChucVu = 5,
                            MaTK = 8,
                            NgaySinh = new DateTime(1996, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0988888888"
                        },
                        new
                        {
                            MaNV = 9,
                            Email = "thu@gmail.com",
                            GioiTinh = false,
                            HoTen = "Ngô Thị Thu",
                            MaChucVu = 6,
                            MaTK = 9,
                            NgaySinh = new DateTime(1995, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0989999999"
                        },
                        new
                        {
                            MaNV = 10,
                            Email = "hung@gmail.com",
                            GioiTinh = true,
                            HoTen = "Trần Văn Hùng",
                            MaChucVu = 5,
                            MaTK = 10,
                            NgaySinh = new DateTime(1994, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0971111111"
                        });
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"), 1L, 1);

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaLoai");

                    b.ToTable("Phongs");

                    b.HasData(
                        new
                        {
                            MaPhong = 101,
                            MaLoai = 1,
                            TenPhong = "P101",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = 102,
                            MaLoai = 1,
                            TenPhong = "P102",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = 201,
                            MaLoai = 2,
                            TenPhong = "P201",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = 202,
                            MaLoai = 3,
                            TenPhong = "P202",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = 301,
                            MaLoai = 4,
                            TenPhong = "P301",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = 302,
                            MaLoai = 5,
                            TenPhong = "P302",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = 303,
                            MaLoai = 2,
                            TenPhong = "P303",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = 304,
                            MaLoai = 3,
                            TenPhong = "P304",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = 305,
                            MaLoai = 4,
                            TenPhong = "P305",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = 306,
                            MaLoai = 5,
                            TenPhong = "P306",
                            TrangThai = "Trống"
                        });
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.TaiKhoan", b =>
                {
                    b.Property<int>("MaTK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTK"), 1L, 1);

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTK");

                    b.HasIndex("MaNV");

                    b.ToTable("TaiKhoans");

                    b.HasData(
                        new
                        {
                            MaTK = 1,
                            MaNV = 1,
                            MatKhau = "123456",
                            TenDangNhap = "huong"
                        },
                        new
                        {
                            MaTK = 2,
                            MaNV = 2,
                            MatKhau = "123456",
                            TenDangNhap = "hay"
                        },
                        new
                        {
                            MaTK = 3,
                            MaNV = 3,
                            MatKhau = "123456",
                            TenDangNhap = "diem"
                        },
                        new
                        {
                            MaTK = 4,
                            MaNV = 4,
                            MatKhau = "123456",
                            TenDangNhap = "an"
                        },
                        new
                        {
                            MaTK = 5,
                            MaNV = 5,
                            MatKhau = "123456",
                            TenDangNhap = "mai"
                        });
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.ChiTietDichVu", b =>
                {
                    b.HasOne("PhanMemQuanLyKhachSan.Model.DichVu", "DichVu")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("MaDV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhanMemQuanLyKhachSan.Model.DatPhong", "DatPhong")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("MaDatPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatPhong");

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.ChiTietHoaDon", b =>
                {
                    b.HasOne("PhanMemQuanLyKhachSan.Model.ChiTietDichVu", "ChiTietDichVu")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaCTDV");

                    b.HasOne("PhanMemQuanLyKhachSan.Model.DatPhong", "DatPhong")
                        .WithMany()
                        .HasForeignKey("MaDatPhong");

                    b.HasOne("PhanMemQuanLyKhachSan.Model.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietDichVu");

                    b.Navigation("DatPhong");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.DatPhong", b =>
                {
                    b.HasOne("PhanMemQuanLyKhachSan.Model.KhachHang", "KhachHang")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhanMemQuanLyKhachSan.Model.Phong", "Phong")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.HoaDon", b =>
                {
                    b.HasOne("PhanMemQuanLyKhachSan.Model.DatPhong", "DatPhong")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaDatPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatPhong");
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.LichPhanCong", b =>
                {
                    b.HasOne("PhanMemQuanLyKhachSan.Model.NhanVien", "NhanVien")
                        .WithMany("LichPhanCongs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.NhanVien", b =>
                {
                    b.HasOne("PhanMemQuanLyKhachSan.Model.ChucVu", "ChucVu")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.Phong", b =>
                {
                    b.HasOne("PhanMemQuanLyKhachSan.Model.LoaiPhong", "LoaiPhong")
                        .WithMany("Phongs")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.TaiKhoan", b =>
                {
                    b.HasOne("PhanMemQuanLyKhachSan.Model.NhanVien", "NhanVien")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.ChiTietDichVu", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.DatPhong", b =>
                {
                    b.Navigation("ChiTietDichVus");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.DichVu", b =>
                {
                    b.Navigation("ChiTietDichVus");
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.KhachHang", b =>
                {
                    b.Navigation("DatPhongs");
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.LoaiPhong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.NhanVien", b =>
                {
                    b.Navigation("LichPhanCongs");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("PhanMemQuanLyKhachSan.Model.Phong", b =>
                {
                    b.Navigation("DatPhongs");
                });
#pragma warning restore 612, 618
        }
    }
}
